### ISSUE TITLE
Conditionals for different software versions

### ISSUE THREAD

**Issue by ProximaNova** [ProximaNova/Booru-mass-editor#18]
``` javascript
if ("Gelbooru Beta 0.1.11") {
    use: "Booru-mass-editor.user.js"
} else if ("Gelbooru Beta 0.2") {
    use: "Booru-mass-editor-for-gelbooru-beta-0.2.user.js"
}
```

**Comment by Seedmanc** [comment]
Doubt there's a userscripting engine that would allow you switching like that. Just put the functionnel into ifs inside one script.

**Comment by ProximaNova** [comment]
Notes with this script on Gelbooru Beta 0.2 &rarr; `&id=` pages ([source](https://github.com/ProximaNova/Booru-mass-editor/commits/master)):
- b22dbe69a2311655624a1f76c43658a959c90605 - not an issue because not all pages load in 10 seconds
- 2384dd00dfaf81aa39eb3a7396a7d1f2ee54fb59 - not an issue because not all pages load in 10 seconds

Notes with the post list improver:
- https://github.com/ProximaNova/Booru-Augmentation-Project/commit/9b759151b9a3b2abb179dfe08a8e59aeaf3522ee
- https://github.com/ProximaNova/Booru-Augmentation-Project/commit/addbdf98b1184fc348ebf1719e126483d62b9f65

**Comment by Seedmanc** [comment]
I don't really understand any of this, be verbose. What is the post list userscript even supposed to achieve?

**Comment by ProximaNova** [comment]
For post list:
- [Keyboard shortcuts](http://danbooru.donmai.us/static/keyboard_shortcuts)
- Fix `'` in links: `%26%23039%3B` &rarr; `%27`
- Fix `"` in links: `%26quot%3B` &rarr; `%22`
- Hide adverts:
  - link with href matching: `https://www.patreon.com/booru`
  - `("#bottom")` (for the newer version)
  - `("#top")` (for the newer version)
- Compact view (done): switch on or off (future)
- Remove excess space at the bottom
- Improve `("#header")` and rearrange links to the blank `("#long-notice")` part
- Future:
  - Fix pagination
  - Pagination links length based on page width

**Comment by Seedmanc** [comment]
I think I already remove ads and fix pagination in BAP. Now working on searching posts by image based on collected post data.

**Comment by ProximaNova** [comment]
Done, there is  conditionals for different URLs that have different software. Also, there are other ways of telling such as the image length (excluding ads): `$("img").length == 20` for Gelbooru Beta 0.1.11 and `42` for Gelbooru Beta 0.2.
