### ISSUE TITLE
Change my tags at ID page

### ISSUE THREAD

**Issue by ProximaNova** [ProximaNova/Booru-mass-editor#5]
It would be great if it was possible.

**Comment by Seedmanc** [comment]
What's the problem? They're kept in cookies, just change those.

**Comment by ProximaNova** [comment]
It is just that I'll have to sort of transclude text "My Tags" textarea to the `&id=` page; I'll do it later.

**Comment by ProximaNova** [comment]
I've sort of transcluded the My Tags textarea but can't submit it when changing it at the ID page.

**Comment by ProximaNova** [comment]
Done.

**Comment by ProximaNova** [comment]
Done, now I have to implement this[1] for the longer tags such as `*_background`, `*_(artist)`, `*_(character)`, and `*_(copyright)`.

1. https://anonmgur.com/up/20b6b418ad355678c19e37d17f9a08ff.png
